apiVersion: v1
kind: Pod
metadata:
  generateName: app
  namespace: banking
  labels:
    purpose: accounting
spec:   
  containers:
    - name:  web-container
      image: pbadhe34/training:webapp
      ports:
        - containerPort: 9090 

  

