apiVersion: v1
kind: Pod
metadata:
  name: pod-py-redis
spec:
  hostNetwork: false
  containers:
    - name: py-app
      image: pbadhe34/my-apps:app2
      ports:
        - containerPort: 8090          
    - name: redis
      image: redis
      ports:
        - containerPort: 6379           
