apiVersion: v1
kind: Pod
metadata:
  name: user-app-pod
spec:
  volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName:  mysql-pv-claim
  containers:
    - name: user-app
      image: pbadhe34/training:web-mysql-local
      ports:
        - containerPort: 8090
       
    - name: mysql-localhost-container
      image: mysql:5.6
      ports:
        - containerPort: 3306
          name: mysql
      env:
         - name: MYSQL_ROOT_PASSWORD
           value: "MyRootPass123" 
         - name: MYSQL_DATABASE
           value: user_data       
      volumeMounts:
          - name: persistent-storage
            mountPath: /var/lib/mysql      
